import { findRepoById } from "../dao/repo.dao.js";
import { findChunksByRepo } from "../dao/chunk.dao.js";
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { ChatMistralAI } from "@langchain/mistralai";
import { ChatCohere } from "@langchain/cohere";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import config from "../config/config.js";

const geminiLLM = new ChatGoogleGenerativeAI({
  apiKey: config.GOOGLE_API_KEY,
  model: "gemini-2.0-flash",
  temperature: 0.3,
});
const mistralLLM = new ChatMistralAI({
  apiKey: config.MISTRAL_API_KEY,
  model: "mistral-small-latest",
  temperature: 0.3,
});
const cohereLLM = new ChatCohere({
  apiKey: config.COHERE_API_KEY,
  model: "command-r",
  temperature: 0.3,
});

const PROVIDERS = [geminiLLM, mistralLLM, cohereLLM];

const invokeWithFallback = async (messages) => {
  let lastError;
  for (const llm of PROVIDERS) {
    try {
      return await llm.invoke(messages);
    } catch (err) {
      lastError = err;
    }
  }
  throw lastError;
};

const buildFolderTree = (files) => {
  const tree = {};
  files.forEach((f) => {
    const parts = f.path.split("/");
    let node = tree;
    parts.forEach((part, i) => {
      if (i === parts.length - 1) {
        node[part] = null; // file leaf
      } else {
        node[part] = node[part] || {};
        node = node[part];
      }
    });
  });
  return tree;
};

const renderTree = (tree, prefix = "") => {
  let output = "";
  const entries = Object.entries(tree);
  entries.forEach(([name, children], i) => {
    const isLast = i === entries.length - 1;
    output += `${prefix}${isLast ? "└── " : "├── "}${name}\n`;
    if (children) {
      output += renderTree(children, prefix + (isLast ? "    " : "│   "));
    }
  });
  return output;
};

export const generateOnboardingDoc = async (repoId) => {
  const repo = await findRepoById(repoId);
  if (!repo) {
    const error = new Error("Repo not found");
    error.statusCode = 404;
    throw error;
  }

  const chunks = await findChunksByRepo(repoId);

  // Summarize the most significant symbols (components/classes) to ground the AI's overview
  const topSymbols = chunks
    .filter((c) => c.chunkType === "component" || c.chunkType === "class")
    .slice(0, 20)
    .map((c) => `- ${c.symbolName} (${c.chunkType}) — ${c.filePath}`)
    .join("\n");

  const folderTreeText = renderTree(buildFolderTree(repo.files));

  const systemPrompt = `You are generating a developer onboarding document for a codebase. Write a concise, practical Markdown document with these sections:

## Overview
A 2-3 sentence summary of what this project appears to be, based on its structure and key components.

## Key Components
Briefly describe the purpose of the most important files/components listed below.

## Getting Started
Generic setup steps a developer would follow (install deps, run dev server) — infer from the file structure (e.g. presence of package.json implies npm install && npm run dev).

Be concise and factual. Do not invent features not evidenced by the file/symbol names.`;

  const userPrompt = `Repository: ${repo.fullName}

Folder structure:
${folderTreeText}

Key symbols found:
${topSymbols || "No components indexed yet."}`;

  const response = await invokeWithFallback([
    new SystemMessage(systemPrompt),
    new HumanMessage(userPrompt),
  ]);

  const generatedSections = response.content;

  const fullDoc = `# ${repo.name} — Onboarding Guide

> Auto-generated by Codebase Copilot

${generatedSections}

## Folder Structure

\`\`\`
${folderTreeText}
\`\`\`

---
*Generated on ${new Date().toISOString().split("T")[0]}*
`;

  return fullDoc;
};